# Generated by Django 2.2.4 on 2019-08-31 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profile'},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
