# Generated by Django 2.2.4 on 2019-08-30 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'catexgory', 'verbose_name_plural': 'categories'},
        ),
    ]
